FROM soneta/web.standard:2412.4.6-alpine

ENV SONETA_SERVER_ENDPOINTS=http://enova-server:22000
ENV SONETA_FRONTEND__SERVERENDPOINT=http://enova-server:22000
ENV SONETA_URLS=http://+:8080
ENV ProductSettings__Settings__AdminPwd=MyWebSecretPassword123
