FROM soneta/web.standard:2504.0.0-alpine

ENV SONETA_SERVER_ENDPOINTS=http://enova-server:22000
ENV SONETA_FRONTEND__SERVERENDPOINT=http://enova-server:22000
ENV SONETA_URLS=http://+:8080
ENV ProductSettings__Settings__AdminPwd=<WebServerAdminPassword>
